# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{phonos}
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lumren Randir"]
  s.date = %q{2010-03-29}
  s.description = %q{Phonos, the Phonosemantics Analyser}
  s.email = %q{lumrandir@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/phonos.rb",
     "lib/phonos/analyzer.rb",
     "lib/phonos/language.rb",
     "lib/string_crutch.rb",
     "phonos.gemspec",
     "test/helper.rb",
     "test/test_phonos.rb"
  ]
  s.homepage = %q{http://feeltoday.ru/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Phonos Phonosemantics Gem}
  s.test_files = [
    "test/test_phonos.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 2.10.3"])
      s.add_runtime_dependency(%q<unicode>, [">= 0.3.1"])
    else
      s.add_dependency(%q<shoulda>, [">= 2.10.3"])
      s.add_dependency(%q<unicode>, [">= 0.3.1"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 2.10.3"])
    s.add_dependency(%q<unicode>, [">= 0.3.1"])
  end
end

